export interface PersonProps {
  id: number;
  name: string;
  unit?: string;
  role?: string;
  department?: string;
}

export const mockPeople: PersonProps[] = [
  {
    id: 1,
    name: "Alexia Kaori Matubara",
    unit: "CASE",
    role: "—",
    department: "—",
  },
  {
    id: 2,
    name: "Ana Cristina Pereira dos Santos",
    unit: "PARHIS",
    role: "—",
    department: "Vistorias",
  },
  {
    id: 3,
    name: "Analice Barbosa dos Santos",
    unit: "CASE",
    role: "—",
    department: "Comunicação",
  },
  {
    id: 4,
    name: "Cristiane Oliveira",
    unit: "CONTRU",
    role: "1ª Secretária",
    department: "Vistorias, Comunicação",
  },
  {
    id: 5,
    name: "Eliana Gonçalves da Luz",
    unit: "CAEPP",
    role: "—",
    department: "SIPAT, Vistorias",
  },
  {
    id: 6,
    name: "Francisco Juvencio da Silva",
    unit: "PARHIS",
    role: "—",
    department: "—",
  },
  {
    id: 7,
    name: "Gabriela Galvão de França",
    unit: "—",
    role: "—",
    department: "—",
  },
  {
    id: 8,
    name: "Georgia Santaniello Abejon",
    unit: "—",
    role: "—",
    department: "Vistorias",
  },
  {
    id: 9,
    name: "Giovanna de Aquino Línica",
    unit: "CAF",
    role: "—",
    department: "CAT",
  },
  {
    id: 10,
    name: "Hélio Freitas Filho",
    unit: "SERVIN",
    role: "2º Secretário",
    department: "Vistorias, comunicação",
  },
  {
    id: 11,
    name: "Isabela Gobbato",
    unit: "RESID",
    role: "—",
    department: "Comunicação",
  },
  {
    id: 12,
    name: "Ivan Xavier Papaterra Limongi",
    unit: "COSH",
    role: "—",
    department: "Vistorias",
  },
  {
    id: 13,
    name: "Janaina Belo de Oliveira",
    unit: "CEPEUC",
    role: "—",
    department: "SIPAT, CAT",
  },
  {
    id: 14,
    name: "Kathleen Maria Horácio Soares",
    unit: "PARHIS",
    role: "—",
    department: "—",
  },
  {
    id: 15,
    name: "Leila Souza Petrini",
    unit: "PARHIS",
    role: "Presidente",
    department: "—",
  },
  {
    id: 16,
    name: "Letícia Soares Honório",
    unit: "PLANURB",
    role: "—",
    department: "CAT",
  },
  {
    id: 17,
    name: "Márcio de Oliveira Soares",
    unit: "GEOINFO",
    role: "—",
    department: "Vistorias, comunicação",
  },
  {
    id: 18,
    name: "Nance de Fátima do Nascimento",
    unit: "CAP/GAB",
    role: "—",
    department: "—",
  },
  {
    id: 19,
    name: "Pamela Borges Silva",
    unit: "—",
    role: "—",
    department: "—",
  },
  {
    id: 20,
    name: "Renan Teixeira Martins",
    unit: "CONTRU/DINS",
    role: "—",
    department: "Vistorias",
  },
  {
    id: 21,
    name: "Ricardo Nagliati Toppan",
    unit: "COSH",
    role: "—",
    department: "SIPAT",
  },
  {
    id: 22,
    name: "Rosemeire de Almeida",
    unit: "GEOINFO",
    role: "Vice-Presidente",
    department: "SIPAT, CAT",
  },
  {
    id: 23,
    name: "Thamires Lima Silva",
    unit: "—",
    role: "—",
    department: "—",
  },
  {
    id: 24,
    name: "Vanderley Silva Pereira Oliveira",
    unit: "CAP/DPCI",
    role: "—",
    department: "SIPAT",
  },
  {
    id: 25,
    name: "Wellington Caetano Silva de Paula",
    unit: "CONTRU/DINS",
    role: "—",
    department: "Vistorias",
  },
  {
    id: 26,
    name: "Zélia Bomfim da Cruz",
    unit: "CAP/DPD",
    role: "—",
    department: "SIPAT",
  },
];
