export const CATALOGO_ATECC = {
  unidade: {
    nome: "Assessoria Técnica de Comissões e Colegiados",
    sigla: "ATECC",
    codigoEh: "291000150000000",
  },
  cargos: [
    {
      nome: "ASO, AAG e Assessor",
      atividades: [
        { categoria: "ADMINISTRATIVO", descricao: "Recepção de solicitações enviadas pelos demais servidores, Solicitações de providências a outros setores internos, Avisos Gerais dentro do setor", pontuacao: 20 },
        { categoria: "ADMINISTRATIVO", descricao: "Registro e solicitação de materiais, Conferência de dados do patrimônio no SBPM, Aceite de movimentação, Checagem de movimentações pendentes", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Organização nas pastas da intranet e Microsoft Teams; Alimentação com documentos e dados faltantes nas pastas do setor", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Criação e atualização de manuais com os procedimentos internos, entre outros", pontuacao: 50 },
        { categoria: "ADMINISTRATIVO", descricao: "Recebimento, conferência e tramitação de processos em ATECC, Aprova Rápido, CEUSO, CAIEPS, CAEHIS, CTLU, CPPU, CMPU, FUNDURB e CIMPDE", pontuacao: 10 },
        { categoria: "ADMINISTRATIVO", descricao: "Geração de relatórios e gráficos diversos sobre o Aprova Rápido, CEUSO, CAIEPS, CAEHIS, CTLU, CPPU, CMPU, FUNDURB, CIMPDE e AIU-VL; Geração de relatório de estoque de processos", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Inclusão e acompanhamento nas planilhas de controle de processos, Acompanhamento de prazos gerais, Publicações via SEI e demais sistemas, Consultas aos sistemas internos e geração de dados", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Recepção e juntada de cartas de desistência, documentos, pedidos de reconsideração de inadmissibilidade e petições diversas, bem como geração de DAMSP", pontuacao: 25 },
        { categoria: "ADMINISTRATIVO", descricao: "Geração de relatórios do SEI e conferência de dados nos documentos e encaminhamentos", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Conferência e auxílio de processos de Ciência do corpo técnico; Auxílio administrativo aos técnicos e ao Chefe de Assessoria", pontuacao: 30 },
        { categoria: "ADMINISTRATIVO", descricao: "Atendimento de dúvidas encaminhadas pela Imprensa de SMUL e outros órgãos internos e externos", pontuacao: 20 },
        { categoria: "ATENDIMENTO", descricao: "Participação nas reuniões virtuais com munícipes para apoio administrativo", pontuacao: 20 },
        { categoria: "ATENDIMENTO", descricao: "Conferência e resposta de e-mails; Auxílio e contato no recebimento, análise e soluções de dúvidas de munícipes; Suporte aos munícipes no protocolo de processos eletrônicos", pontuacao: 30 },
        { categoria: "ATENDIMENTO", descricao: "Atendimentos e auxílio das demandas de marcação e alteração de férias, Esclarecimentos de dúvidas aos servidores do setor, Conferências das folhas de frequência digitalizadas, Mediação pelos elos para troca de informação com o setor de recursos humanos", pontuacao: 30 },
        { categoria: "COLEGIADOS", descricao: "Auxílio na preparação e organização das reuniões das Comissões (levantamento de processos, elaboração da pauta, convocação, preparação e conferência de documentos, entre outros)", pontuacao: 40 },
        { categoria: "COLEGIADOS", descricao: "Participação nas reuniões das Comissões para apoio administrativo", pontuacao: 50 },
        { categoria: "COLEGIADOS", descricao: "Redação de informações, manifestações, listas de presenças, atas, pronunciamentos e despachos, a partir das deliberações do Plenário", pontuacao: 30 },
        { categoria: "COLEGIADOS", descricao: "Aviso, suporte aos membros das Comissões com as assinaturas digitais, controle e cobrança de pendências no pós-reunião", pontuacao: 20 },
        { categoria: "COLEGIADOS", descricao: "Atualização de atas, deliberações, calendários e lista de membros no site da prefeitura", pontuacao: 20 },
        { categoria: "COLEGIADOS", descricao: "Preparação da eleição das Comissões e Colegiados", pontuacao: 50 },
      ],
    },
    {
      nome: "Arquitetos",
      atividades: [
        { categoria: "Análise Técnica", descricao: "Análise no SEI, SLC e Aprova Digital", pontuacao: 10 },
        { categoria: "Análise Técnica", descricao: "Admissibilidade do Aprova Rápido", pontuacao: 15 },
        { categoria: "Análise Técnica", descricao: "Processos físicos digitalizados", pontuacao: 10 },
        { categoria: "Análise Técnica", descricao: "FUNDURB (processos e balancetes)", pontuacao: 20 },
        { categoria: "Análise Técnica", descricao: "Execução orçamentária", pontuacao: 20 },
        { categoria: "Relatórios", descricao: "Elaboração e revisão de manifestações", pontuacao: 25 },
        { categoria: "Relatórios", descricao: "Relatoria na CTLU", pontuacao: 30 },
        { categoria: "Relatórios", descricao: "Propostas, resoluções e normas", pontuacao: 40 },
        { categoria: "Relatórios", descricao: "Demandas relacionadas a Projetos de Lei", pontuacao: 40 },
        { categoria: "Administrativo", descricao: "Apoio ao setor técnico", pontuacao: 10 },
        { categoria: "Administrativo", descricao: "Planilhas de controle", pontuacao: 10 },
        { categoria: "Administrativo", descricao: "Ofícios e memorandos via SEI", pontuacao: 15 },
        { categoria: "Comissões", descricao: "Organização e participação", pontuacao: 30 },
        { categoria: "Comissões", descricao: "Apresentações técnicas", pontuacao: 30 },
        { categoria: "Comissões", descricao: "Eleições do CMPU e AIU-VL", pontuacao: 50 },
        { categoria: "Atendimento", descricao: "Atendimento à imprensa", pontuacao: 20 },
        { categoria: "Atendimento", descricao: "Atendimento a munícipes", pontuacao: 20 },
        { categoria: "Atendimento", descricao: "Reuniões virtuais", pontuacao: 20 },
        { categoria: "Atendimento", descricao: "Outras demandas definidas pela chefia", pontuacao: 10 },
      ],
    },
    {
      nome: "Arquitetos com cargo de Assessor",
      atividades: [
        { categoria: "Análise Técnica", descricao: "Análise, Revisão e Validação Técnica", pontuacao: 30 },
        { categoria: "Gestão", descricao: "Supervisão, Coordenação e Controle", pontuacao: 40 },
        { categoria: "Estratégico", descricao: "Produção de Documentos Estratégicos", pontuacao: 50 },
        { categoria: "Comissões", descricao: "Atuação em Comissões (com relatoria)", pontuacao: 50 },
        { categoria: "Relacionamento", descricao: "Atendimento e Relações Institucionais", pontuacao: 30 },
      ],
    },
  ],
  servidores: [
    { rf: "8000001", nome: "ALESSANDRO", cargo: "ASO, AAG e Assessor", grupo: 1 },
    { rf: "8000002", nome: "CECILIA", cargo: "ASO, AAG e Assessor", grupo: 1 },
    { rf: "8000003", nome: "GABRIEL", cargo: "ASO, AAG e Assessor", grupo: 1 },
    { rf: "8000004", nome: "ERICA", cargo: "Arquitetos com cargo de Assessor", grupo: 1 },
    { rf: "8000005", nome: "PAULA", cargo: "Arquitetos com cargo de Assessor", grupo: 1 },
    { rf: "8000006", nome: "MARIANA", cargo: "Arquitetos com cargo de Assessor", grupo: 1 },
    { rf: "8000007", nome: "ANA", cargo: "Arquitetos", grupo: 1 },
    { rf: "8000008", nome: "RENAN", cargo: "Arquitetos", grupo: 1 },
    { rf: "8000009", nome: "THAYS", cargo: "Arquitetos", grupo: 1 },
    { rf: "8000010", nome: "MARCO", cargo: "ASO, AAG e Assessor", grupo: 2 },
    { rf: "8000011", nome: "MARCOS", cargo: "ASO, AAG e Assessor", grupo: 2 },
    { rf: "8000012", nome: "THIAGO", cargo: "ASO, AAG e Assessor", grupo: 2 },
    { rf: "8000013", nome: "HENRIQUE", cargo: "ASO, AAG e Assessor", grupo: 2 },
    { rf: "8000014", nome: "MARILIA", cargo: "Arquitetos com cargo de Assessor", grupo: 2 },
    { rf: "8000015", nome: "ROSANA", cargo: "Arquitetos com cargo de Assessor", grupo: 2 },
    { rf: "8000016", nome: "FERNANDA", cargo: "Arquitetos", grupo: 2 },
    { rf: "8000017", nome: "MARIELY", cargo: "Arquitetos", grupo: 2 },
    { rf: "8000018", nome: "GIL", cargo: "Arquitetos", grupo: 2 },
  ],
} as const;
