/** @format */

export const mockPosts = [
  {
    id: 1,
    author: "Coordenadoria de Comunicação",
    cargo: "Comunicação SMUL",
    time: "há 1h",
    type: "comunicado",
    text: "Já conferiu se o seu cadastro está atualizado? Atualize seus dados de contato no portal do servidor para mantermos uma comunicação assertiva. É simples e rápido!",
    image: "figma-assets/banner-comunicado.png",
    likes: 34,
    likedByMe: false,
    commentsOpen: false,
    draft: "",
    comments: [
      {
        author: "Sandra Maria Coelho Cruz",
        text: "Feito! Muito importante essa atualização.",
        initials: "SC",
        avatarColor: "#8B5CB0",
      },
    ],
  },
  {
    id: 2,
    author: "Ingrid Jesus Costa",
    cargo: "Divisão de Gestão de Pessoas",
    time: "há 3h",
    type: "kudos",
    text: "Quero reconhecer o time da CASE pelo excelente trabalho na migração do sistema de licenciamento este mês. Dedicação exemplar! 👏 (sem emoji, só orgulho mesmo)",
    image: null,
    likes: 21,
    likedByMe: true,
    commentsOpen: false,
    draft: "",
    comments: [],
  },
  {
    id: 3,
    author: "Urbanismo em Pauta",
    cargo: "Cultura urbana",
    time: "há 5h",
    type: "comum",
    text: "Papo Urbano deste mês: uma releitura visual da região central de São Paulo. Confira a matéria completa na aba Comunicados.",
    image: "figma-assets/news-photo-1.png",
    likes: 12,
    likedByMe: false,
    commentsOpen: false,
    draft: "",
    comments: [],
  },
  {
    id: 4,
    author: "Rogério do N. Gonçalves",
    cargo: "RESID",
    time: "há 1 dia",
    type: "vaga",
    text: "Estamos com uma vaga interna aberta na Coordenadoria de Licenciamento para analista pleno. Interessados podem procurar a DSIGP até sexta-feira.",
    image: null,
    likes: 8,
    likedByMe: false,
    commentsOpen: false,
    draft: "",
    comments: [],
  },
  {
    id: 5,
    author: "Coordenadoria de Tecnologia da Informação",
    cargo: "TI · Suporte",
    time: "há 2 dias",
    type: "conquista",
    text: "Celebramos 3 anos do GeoSampa 2.0 no ar, com mais de 40 mil acessos mensais. Obrigado a todos que tornaram esse projeto possível!",
    image: null,
    likes: 45,
    likedByMe: false,
    commentsOpen: false,
    draft: "",
    comments: [],
  },
] as const;
